// Headless economy check: bots play 3 in-game years through the real sim API.
// npm run balance            prints the milestone table and checks targets (exit 1 on a miss)
// npm run balance -- --write also writes the table to docs/BALANCE.md
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runBot, type Milestones } from './bots';
import * as sim from '../src/sim/index';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const YEARS = Number(args[args.indexOf('--years') + 1]) || 3;
const DAYS = 98 * YEARS;
const SEEDS = [101, 202, 303, 404];
const EXPERT_DAYS = 98 * 4;

interface Row { bot: string; seed: number; m: Milestones; cash: number; clients: number; valuation: number; rep: number; staff: number; crews: number; towns: number }

const rows: Row[] = [];
const t0 = Date.now();
for (const bot of ['novice', 'solid', 'expert'] as const) {
  for (const seed of SEEDS) {
    const days = bot === 'expert' ? Math.max(DAYS, EXPERT_DAYS) : DAYS;
    const { state, m } = runBot(bot, seed, days);
    rows.push({
      bot, seed, m, cash: Math.round(state.cash), clients: state.clients.length, valuation: sim.valuation(state).total,
      rep: sim.reputation(state), staff: state.staff.length, crews: state.crews.length, towns: state.towns.length,
    });
    process.stdout.write('.');
  }
}
process.stdout.write('\n');

const fmt = (x: number | null) => (x === null ? 'never' : String(x));
const money = (x: number) => (Math.abs(x) >= 1e6 ? `$${(x / 1e6).toFixed(2)}M` : `$${Math.round(x / 1000)}k`);
const lines: string[] = [];
lines.push('| bot | seed | gas mower | truck | first hire | zero-turn | first bid | clients at season ends | min cash | final cash | valuation Y1 / Y2 / Y3 | $1M day | rep | staff | crews | towns |');
lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const r of rows) {
  const v = [1, 2, 3].map((y) => (r.m.valuationAt[y] !== undefined ? money(r.m.valuationAt[y]) : '-')).join(' / ');
  lines.push(`| ${r.bot} | ${r.seed} | ${fmt(r.m.gas)} | ${fmt(r.m.truck)} | ${fmt(r.m.hire)} | ${fmt(r.m.zeroTurn)} | ${fmt(r.m.bid)} | ${r.m.seasonClients.slice(0, 12).join(', ')} | ${money(r.m.minCash)} | ${money(r.cash)} | ${v} | ${fmt(r.m.million)} | ${r.rep.toFixed(2)} | ${r.staff} | ${r.crews} | ${r.towns} |`);
}
console.log(lines.join('\n'));

// ---------------------------------------------------------------- targets
const median = (xs: number[]) => { const s = [...xs].sort((a, b) => a - b); return s.length ? s[Math.floor((s.length - 1) / 2)] : NaN; };
const of = (bot: string, f: (r: Row) => number | null) => rows.filter((r) => r.bot === bot).map((r) => f(r) ?? 99999);
const checks: { name: string; ok: boolean; value: string }[] = [];
const within = (name: string, xs: number[], lo: number, hi: number) => {
  const m = median(xs);
  checks.push({ name: `${name} in ${lo} to ${hi}`, ok: m >= lo && m <= hi, value: `median ${m === 99999 ? 'never' : m}` });
};
within('solid: gas push mower day', of('solid', (r) => r.m.gas), 0, 3);
within('solid: truck day', of('solid', (r) => r.m.truck), 7, 20);
within('solid: first hire day', of('solid', (r) => r.m.hire), 18, 50);
within('solid: zero-turn day', of('solid', (r) => r.m.zeroTurn), 15, 45);
checks.push({ name: 'solid: solvent (min cash > -$500)', ok: rows.filter((r) => r.bot === 'solid').every((r) => r.m.minCash > -500), value: rows.filter((r) => r.bot === 'solid').map((r) => Math.round(r.m.minCash)).join(', ') });
checks.push({ name: 'novice: never bankrupt (min cash > -$500)', ok: rows.filter((r) => r.bot === 'novice').every((r) => r.m.minCash > -500), value: rows.filter((r) => r.bot === 'novice').map((r) => Math.round(r.m.minCash)).join(', ') });
checks.push({ name: 'novice: slower than solid (truck later or valuation lower)', ok: median(of('novice', (r) => r.valuation)) < median(of('solid', (r) => r.valuation)), value: `${money(median(of('novice', (r) => r.valuation)))} vs ${money(median(of('solid', (r) => r.valuation)))}` });
within('expert: $1M valuation day (within 4 years)', of('expert', (r) => r.m.million), 0, EXPERT_DAYS);

console.log('');
for (const c of checks) console.log(`${c.ok ? 'PASS' : 'FAIL'}  ${c.name}  (${c.value})`);
console.log(`\n${rows.length} runs in ${((Date.now() - t0) / 1000).toFixed(1)} s`);

if (args.includes('--write')) {
  const md = [
    '# Balance report',
    '',
    `Generated by \`npm run balance -- --write\`. Bots play through the real sim API (tools/bots.ts): novice (manual Q about N(70, 8), 6 knocks a day), solid (Q about N(84, 6), 10 knocks, greedy upgrades with a cash reserve, hires when the owner falls behind, autopilot), expert (Q about N(92, 4), 12 knocks, prices near R, sales reps, bids, marketing, branches). ${YEARS} years for novice and solid, 4 for expert, seeds ${SEEDS.join(', ')}. Days are counted from day 0.`,
    '',
    lines.join('\n'),
    '',
    '## Targets',
    '',
    ...checks.map((c) => `- ${c.ok ? 'Pass' : 'Miss'}: ${c.name} (${c.value})`),
    '',
  ].join('\n');
  fs.writeFileSync(path.join(ROOT, 'docs', 'BALANCE.md'), md);
  console.log('Wrote docs/BALANCE.md');
}
process.exit(checks.every((c) => c.ok) ? 0 : 1);
